sudo: required

language: node_js

node_js:
  - 12
  - 10
  - 8

services:
  - mongodb 

env:
  global:
    - MONGODB_VERSION=4.0

before_install:
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
  - echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org
  - sudo service mongod start

install:
  - npm install

script:
  -  npm test  
