language: node_js
node_js:
  - 10
  - 8
  - 6
install:
  - npm install
script:
  - mocha tests/*  
env:
  - TEST_PATH = "/home/travis/build/sergiogp98/MultimediaManagement/lib/database/data/films.json"