version: '3.7'

services:
  database:
    build: .
    image: python:3.7
    volumes:
      - ./database:/database
    working_dir: /database
  
  flask:
    build:
      context: .
      dockerfile: Dockerfile_Flask
    ports:
      - "8080":"5000"
    volumes:
      - ./flask:/flask
    working_dir: /flask
