version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: 'Install all dependencies'
          command: npm install
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: 'Run the tests'
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test