version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
      - image: circleci/mongo:latest
        port: 27017:27017
        #environment:
        #  - MONGODB_USERNAME: "Sergio"
        #  - MONGODB_PASSWORD: "admin"

    steps:
      - run:
          name: Wait fo Mongo
          command: dockerize -wait tcp://localhost:27017 -timeout 1m 
      - checkout
      - run:
          name: 'Install all dependencies'
          command: npm install
      - run:
          name: 'Run the tests'
          command: npm test