version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: .
    steps:
      - checkout
      - run:
          name: 'Install all dependencies'
          command: npm install
      - run:
          name: 'Run tests for latest version of node'
          command: npm test