version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: 'Install all dependencies'
          command: npm install
          name: 'Run the tests'
          command: npm test